export const USER_REPOSITORY = 'USER_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const WAREHOUSE_REPOSITORY = 'WAREHOUSE_REPOSITORY';
export const ZONE_REPOSITORY = 'ZONE_REPOSITORY';
export const LOCATION_REPOSITORY = 'LOCATION_REPOSITORY';
